#pragma once
enum NetMessage
{
	GM_CREATE_ACCOUNT,			//创建账号
	GM_CREATE_ACCOUNT_RESPONSE,

	GM_ACCOUNT_CHECK,
	GM_ACCOUNT_CHECK_RESPONSE,

	GM_CREATE_PLAYER,
	GM_CREATE_PLAYER_RESPONSE,	

	GM_LOGIN,
	GM_LOGIN_RESPONSE,

	PLAYERMESSAGEBEGIN = 10000,

	GM_REQUEST_MOVE = 10100,				//请求玩家移动
	GM_NOTIFY_MOVEING,						//广播玩家移动
	GM_REQUEST_USE,							//请求使用道具
	GM_USE_RESPONSE,	
	PLAYERMESSAGEEND,
};