module.exports = {
	"GM_CREATE_ACCOUNT":0,			//创建账号
	"GM_CREATE_ACCOUNT_RESPONSE":1,
	"GM_ACCOUNT_CHECK":2,
	"GM_ACCOUNT_CHECK_RESPONSE":3,
	"GM_CREATE_PLAYER":4,
	"GM_CREATE_PLAYER_RESPONSE":5,	
	"GM_LOGIN":6,
	"GM_LOGIN_RESPONSE":7,
	"PLAYERMESSAGEBEGIN ": 10000,
	"GM_REQUEST_MOVE ": 10100,				//请求玩家移动
	"GM_NOTIFY_MOVEING":10101,						//广播玩家移动
	"GM_REQUEST_USE":10102,							//请求使用道具
	"GM_USE_RESPONSE":10103,	
	"PLAYERMESSAGEEND":10104,
};
